[workspace]
channels = ["conda-forge"]
name = "MMH_Analysis_Package"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
bulk = "python src/test.py bulk"

[dependencies]
numpy = ">=2.3.1,<3"
click = ">=8.2.1,<9"
mdanalysis = ">=2.9.0,<3"
pydantic = ">=2.11.7,<3"
mdtraj = ">=1.11.0,<2"
ipykernel = ">=6.29.5,<7"