[workspace]
authors = ["Troy Smith <Troy.Smith@uga.edu>"]
channels = ["conda-forge"]
name = "MMH_Analysis_Package"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
mdanalysis = ">=2.9.0,<3"
mdtraj = ">=1.11.0,<2"
click = ">=8.2.2,<9"
dask = ">=2025.7.0,<2026"
openpyxl = ">=3.1.5,<4"
ipykernel = ">=6.30.1,<7"
pip = ">=25.2,<26"
